
services:
  db:
    image: postgres:15
    container_name: blog_container_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        backend:
          aliases:
            - database

  backend:
    build: . 
    container_name: blog_app
    ports:
      - "8080:8080"
    env_file:
      - config.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - application


networks:
  backend:
    driver: bridge
