
services:
  db:
    image: postgres:15
    container_name: blog_container_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blog
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
        blog:
          aliases:
            - database

  backend:
    build: . 
    container_name: backend_container
    ports:
      - "8080:8080"
    env_file:
      - config.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      blog:
        aliases:
          - backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8080 
    depends_on:
      - backend
    container_name: frontend_container
    networks:
      - blog
networks:
  blog:
    driver: bridge
