definitions:
    APIError:
        description: Стандартная ошибка API
        properties:
            code:
                format: int64
                type: integer
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
        type: object
        x-go-package: blog/pkg/handlers
    Response:
        description: Стандартный ответ API
        properties:
            code:
                format: int64
                type: integer
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
        type: object
        x-go-package: blog/pkg/models
    article:
        description: Article представляет контентную публикацию
        properties:
            author:
                description: Отображаемое имя автора
                example: Иван Иванов
                type: string
                x-go-name: Author
            id:
                description: Уникальный идентификатор статьи
                example: 1
                format: int64
                type: integer
                x-go-name: ID
            text:
                description: Основное содержимое статьи
                example: Текст статьи...
                type: string
                x-go-name: Text
            user_id:
                description: ID пользователя-владельца статьи
                example: 5
                format: int64
                type: integer
                x-go-name: UserID
        required:
            - id
            - author
            - user_id
            - text
        type: object
        x-go-name: Article
        x-go-package: blog/pkg/models
    postgresDBParams:
        description: Параметры подключения к БД
        properties:
            dbName:
                type: string
                x-go-name: DBName
            host:
                type: string
                x-go-name: Host
            password:
                type: string
                x-go-name: Password
            sslmode:
                type: string
                x-go-name: SslMode
            user:
                type: string
                x-go-name: User
        type: object
        x-go-package: blog/pkg/dbwork
    request:
        description: Request представляет составной входной объект
        properties:
            article:
                $ref: '#/definitions/article'
            user:
                $ref: '#/definitions/user'
        required:
            - article
            - user
        type: object
        x-go-name: Request
        x-go-package: blog/pkg/models
    user:
        description: User представляет учётную запись пользователя
        properties:
            id:
                description: Уникальный идентификатор пользователя
                example: 5
                format: int64
                type: integer
                x-go-name: ID
            login:
                description: Логин для аутентификации
                example: user123
                type: string
                x-go-name: Login
            password:
                description: Пароль учётной записи
                format: password
                type: string
                x-go-name: Password
        required:
            - id
            - login
            - password
        type: object
        x-go-name: User
        x-go-package: blog/pkg/models
paths:
    /article:
        get:
            operationId: getAllArticles
            responses:
                "200":
                    $ref: '#/responses/articlesResponse'
                "500":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
            summary: Получение всех статей
            tags:
                - article
        put:
            description: Требует аутентификации и проверки владельца.
            operationId: updateArticle
            parameters:
                - description: Bearer токен
                  in: header
                  name: Authorization
                  required: true
                  type: string
            responses:
                "200":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "400":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "401":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "403":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "500":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
            summary: Обновление статьи
            tags:
                - article
    /article/{id}:
        delete:
            description: Требует аутентификации и проверки владельца.
            operationId: deleteArticle
            parameters:
                - description: Bearer токен
                  in: header
                  name: Authorization
                  required: true
                  type: string
            responses:
                "200":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "400":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "401":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "403":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "500":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
            summary: Удаление статьи
            tags:
                - article
        get:
            operationId: getArticle
            responses:
                "200":
                    $ref: '#/responses/articleResponse'
                "400":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "404":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "500":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
            tags:
                - article
    /login:
        post:
            operationId: login
            responses:
                "200":
                    $ref: '#/responses/jwtToken'
                "400":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "401":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "500":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
            summary: Аутентификация
            tags:
                - user
    /register:
        post:
            operationId: register
            responses:
                "201":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "400":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "409":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
                "500":
                    description: Response
                    schema:
                        $ref: '#/definitions/Response'
            summary: Регистрация пользователя
            tags:
                - user
responses:
    articleResponse:
        description: ""
        schema:
            $ref: '#/definitions/article'
    articlesResponse:
        description: ""
        schema:
            items:
                $ref: '#/definitions/article'
            type: array
    jwtToken:
        description: ""
        schema:
            properties:
                token:
                    type: string
                    x-go-name: Token
            type: object
swagger: "2.0"
